Service: Added support for the KVMService
kubearmor/KVMService pull request #3
Opened 2021-09-13 07:31 UTC by Maddy007-maha

Description: Created the service and core components which handles the
             CRDs of the KEWService and KubeArmor Host policies.

2021-09-14 16:24 UTC, nyrahul requested changes
pls check the comments.

2021-09-14 16:24 UTC, nyrahul commented on kewpolicy.yaml
> +  ipv4-alloc-cidr: 10.192.1.0/30
ipv4-alloc-cidr is not needed

2021-09-24 05:47 UTC, Maddy007-maha commented on deployments/CRD/KubeArmorExternalWorkloadPolicy.yaml
> +              ipv4-alloc-cidr:
Removed this complete spec section!

2021-09-24 05:47 UTC, Maddy007-maha commented on deployments/CRD/KubeArmorExternalWorkloadPolicy.yaml
> +              ipv6-alloc-cidr:
Removed this complete spec section!

2021-09-24 05:47 UTC, Maddy007-maha commented on kewpolicy.yaml
> +  ipv4-alloc-cidr: 10.192.1.0/30
Removed this complete spec section!

2021-09-24 05:50 UTC, Maddy007-maha commented on README.md
> +## Introduction to KubeArmor KVMS Service
Made it KVMService

2021-09-26 12:20 UTC, nyrahul approved these changes

2021-09-26 13:04 UTC, merged